### ISSUE TITLE
Support for custom key binds with Windows Ink mode plugin

### ISSUE THREAD

**Issue by sbstratos79** [X9VoiD/VoiDPlugins#8]
Windows Ink feature doesn't let the user use  key combinations and certain mouse clicks as key binds. I think the mode becomes almost useless without the keybind combos. Having to scroll using a scrollbar or zoom in with Ctrl++ instead of Ctrl+Pan in a painting program is way too tedious.

**Comment by Mrcubix** [comment]
-> https://www.autohotkey.com/

**Comment by sbstratos79** [comment]
Thanks. I have been reading the Autohotkey manual since posting the original issue on the OpenTabletDriver repository. It's much harder than it seems since I have to make use of external libraries, like AHKHID or AHI. Especially since I have no experience with programming. Native support for hotkey combos in driver would definitely be very useful for people who aren't very well versed with programming, AutoHotkey or both.

**Comment by X9VoiD** [comment]
Will close issue since windows ink and vmulti bindings are explicit now on latest dev build. If you meant multi key bindings (two keys binded to a single pen/tablet button) then OTD does not internally support it yet (at that point this is not the plugin's issue anymore). And if you meant your "painting software" does not respond to hotkeys after using windows ink plugin then it's not windows ink's problem since it never touched keyboard input at the very first place.
